# Straight 1x setup for low-resolution displays like 1080p or 1440p
# t590A
 env = GDK_SCALE,1
#Gigabyte
 monitor=DP-2,3840x2160@144,auto,1

# Fallback for any other monitor
monitor=,preferred,auto,1
